### PR TITLE
Bubble-sort method

### PR DESCRIPTION
**Pull request by mihrab34**

### CODE REVIEW

**Comment by mihrab34** [comment]
Hi Tse(s),

There was a mistake on the commit made by my partner, it was pushed to master instead of the feature branch, we were unable to unmerge but we fixed it by opening another pull request.

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi Team,
You have done a good on this project.
Here  are two tiny things we have to take care of to have this project approved
* [ ] bubble_sort_by method is implemented and working (covered by automated tests).
The test you provided isn't working but returns error at my end🙂.
> you need to modify the test example for it to run
* [ ] IF NOT CAUGHT BY RUBOCOP make sure that code is clean: indentation with two spaces, line lengths, spaces around operators🙂.
> Always remember to run the command ``` rubocop -a``` to take care of the requirement above before submitting your ruby codes for review🙂.
## That is it guys, Kindly do these changes and submit for review.
Feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. I would be happy to assist you.
### Happy coding🙂
### Addo Boakye Forison

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi Team🙂, 
Good job, indentation is good now🙂 but the last problem mentioned in the previous review persists
- [ ] bubble_sort_by method is implemented and working 🙂
```
- p bubble_sort_by %w[hi hello hey] do |left, right|
       left.length - right.length
     end

-   r = ["hi", "hey", "hello"]
    p bubble_sort_by(r) { |left, right| left.length - right.length }

return errors
main.rb:27:in `block (2 levels) in bubble_sort_by': no block given (yield) (LocalJumpError)
```
## That is it kindly make this change submit code for review
#### Happy coding
### Addo Boakye Forison

**Review by suretrust — APPROVED** [review]
Hi team! :raised_hands: 

### Amazing job! Let's get this merged! :+1: 

_Good luck with your future projects and happy coding!_ :tada:

**Pull request merged**
